### ISSUE TITLE
[Dungeon] Dire Maul: North - Guard Slip'kik and Guard Moldar abilities

### ISSUE THREAD

**Issue by whammyresilience** [KurthosWoW/TrinityCore#8]
**Current behaviour:**

Guard Slip'kik and Guard Moldar are both missing the following abilities: Cleave, Shield Slam

https://classicdb.ch/?npc=14323#abilities
https://classicdb.ch/?npc=14326#abilities

**Comment by natnat201193** [comment]
Slip'kik is also giving the wrong dialog while you have the king of fire maul buff, he should be offering the 2 hour buff he gives, but instead the dialog the get is as if you had just trapped him with the freezing trap. i think

**Comment by HelloKitty** [comment]
Can't implement shield slam until we know exactly how it worked in Vanilla. I don't know if it targeted tank, that changes things a lot if it targets the tank. I'll look into the rest.

**Comment by HelloKitty** [comment]
I think the dialog is correct. I think it is missing the 2h buff though. What is he suppose to say if he's not suppose to say that and call ya "Boss"?

**Comment by natnat201193** [comment]
yes, sorry. i actually double checked this and did the full tribute again and all three buffs where available. so i would ignore that part for now.

**Comment by HelloKitty** [comment]
Yea, turns out it was already fixed. I wasted my time trying to fix it, the whole time I was level 80 and it for some reason doesn't work above a certain level.

Also, the creatures cast the missing things now. Except stuns, I need data showing targeting for the stuns. Does it target melee? Does it target tanks? Etc, so this will be left open I guess.
