### ISSUE TITLE
[NPC] Marudon (Outside) - Cavindra - Pathing

### ISSUE THREAD

**Issue by whammyresilience** [KurthosWoW/TrinityCore#97]
**Current behaviour:**

Currently Cavindra is standing in a [strange position](https://imgur.com/a/EZtUCpe) and does not path. 

**Expected behaviour:**

Can't find any proof of a specific path but the picture definitely doesn't look like that's how it should be.

**Steps to reproduce the problem:**

Go visit her inside the entrance to Marudon.

**Comment by natnat201193** [comment]
according to wowhead comments, she just stands in the water. checked on retail and she also has random movement. so going to assume this hasnt been changed since vanilla.

`UPDATE `creature` SET `position_x`='-1458.039063', `position_y`='2797.462646', `position_z`='93.77252', `orientation`='3.578274', `spawndist`='6', `MovementType`='1' WHERE  `guid`=29063;
UPDATE `creature_template` SET `MovementType`='1' WHERE  `entry`=13697;`

**Comment by natnat201193** [comment]
- [ ] gg
